package com.haircut.dao;

import com.haircut.dataobject.SequenceDO;
import com.haircut.dataobject.SequenceDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Jun 09 08:05:39 CST 2022
     */
    long countByExample(SequenceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Jun 09 08:05:39 CST 2022
     */
    int deleteByExample(SequenceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Jun 09 08:05:39 CST 2022
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Jun 09 08:05:39 CST 2022
     */
    int insert(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Jun 09 08:05:39 CST 2022
     */
    int insertSelective(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Jun 09 08:05:39 CST 2022
     */
    List<SequenceDO> selectByExample(SequenceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Jun 09 08:05:39 CST 2022
     */
    SequenceDO selectByPrimaryKey(String name);

    SequenceDO getSequenceByName(String name);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Jun 09 08:05:39 CST 2022
     */
    int updateByExampleSelective(@Param("record") SequenceDO record, @Param("example") SequenceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Jun 09 08:05:39 CST 2022
     */
    int updateByExample(@Param("record") SequenceDO record, @Param("example") SequenceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Jun 09 08:05:39 CST 2022
     */
    int updateByPrimaryKeySelective(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Jun 09 08:05:39 CST 2022
     */
    int updateByPrimaryKey(SequenceDO record);
}