package com.haircut.dao;

import com.haircut.dataobject.StaffDO;
import com.haircut.dataobject.StaffDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StaffDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    List<StaffDO> listStaff();

    long countByExample(StaffDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int deleteByExample(StaffDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int insert(StaffDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int insertSelective(StaffDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    List<StaffDO> selectByExample(StaffDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    StaffDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int updateByExampleSelective(@Param("record") StaffDO record, @Param("example") StaffDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int updateByExample(@Param("record") StaffDO record, @Param("example") StaffDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int updateByPrimaryKeySelective(StaffDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int updateByPrimaryKey(StaffDO record);
}