package com.haircut.dao;

import com.haircut.dataobject.StaffStockDO;
import com.haircut.dataobject.StaffStockDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StaffStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_stock
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    long countByExample(StaffStockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_stock
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int deleteByExample(StaffStockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_stock
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_stock
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int insert(StaffStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_stock
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int insertSelective(StaffStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_stock
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    List<StaffStockDO> selectByExample(StaffStockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_stock
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    StaffStockDO selectByPrimaryKey(Integer id);

    StaffStockDO selectByStaffId(Integer staffId);

    int decreaseStock(@Param("staffId") Integer staffId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_stock
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int updateByExampleSelective(@Param("record") StaffStockDO record, @Param("example") StaffStockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_stock
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int updateByExample(@Param("record") StaffStockDO record, @Param("example") StaffStockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_stock
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int updateByPrimaryKeySelective(StaffStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_stock
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    int updateByPrimaryKey(StaffStockDO record);
}