package com.haircut.dataobject;

public class StaffStockDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_stock.id
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_stock.stock
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_stock.staff_id
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    private Integer staffId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_stock.id
     *
     * @return the value of staff_stock.id
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_stock.id
     *
     * @param id the value for staff_stock.id
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_stock.stock
     *
     * @return the value of staff_stock.stock
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_stock.stock
     *
     * @param stock the value for staff_stock.stock
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_stock.staff_id
     *
     * @return the value of staff_stock.staff_id
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_stock.staff_id
     *
     * @param staffId the value for staff_stock.staff_id
     *
     * @mbg.generated Wed Jun 08 15:06:36 CST 2022
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }
}